basic.forever(function () {
    let van_wijkstraat = 
    let utrechtse_weg = 0
    let vermeerstraat = 0
    let arhnemseweg = 0
    let ringwegranderbroek = 0
    let ringwegkruiskamp = 0
    let leusderweg = 0
    if (leusderweg > 20) {
    	
    } else {
    	
    }
    if (ringwegkruiskamp > 20) {
    	
    } else {
    	
    }
    if (ringwegranderbroek > 20) {
    	
    } else {
    	
    }
    if (arhnemseweg > 20) {
    	
    } else {
    	
    }
    if (vermeerstraat > 20) {
    	
    } else {
    	
    }
    if (utrechtse_weg > 20) {
    	
    } else {
    	
    }
    if (van_wijkstraat > 20) {
    	
    } else {
    	
    }
})
